name: "release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of this pathfinder release. This will create a new tag (triggering docker action) and also set the package version."
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update pathfinder package version
        run: |
          sed -i -e 's/version = ".*"/version = "${{ github.event.inputs.version }}"/' crates/pathfinder/Cargo.toml
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "feat: update package version to ${{ github.event.inputs.version }}"
          git tag v${{ github.event.inputs.version }}

      - name: Push commit to origin
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Create release notes draft
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
              /repos/Mirko-von-Leipzig/release_tester/releases \
            -f tag_name='v${{ github.event.inputs.version }}' \
            -f target_commitish='master' \
            -f name='v${{ github.event.inputs.version }}' \
            -f body='Description of the release' \
            -F draft=true \
            -F prerelease=false \
            -F generate_release_notes=true 